### ISSUE TITLE
Technical implementation of adding metadata

### ISSUE THREAD

**Issue by marev711** [cerfacs-globc/icclim#15]
A sub issue is to add reference data in the output file.

**Comment by MilkaRadojevic** [comment]
Corresponding _global_ meta-data are ready but waiting for a feedback from KNMI.

**Comment by marev711** [comment]
Ok, so once their feedback is in we can, given other priorities, look into the technical implementation of writing meta data to output  files and what kind of format (txt, json, config)  is most efficient to store the meta data in ICCLIM.

**Comment by MilkaRadojevic** [comment]
There are two types of metadata in our case: 1) fixed text that we create for both index variable and global attributes, and 2) the part of global metadata that needs to be extracted from global attributes of the input files. We should think how to deal with the 2nd since the 1st is easy. We suggest use of .json as more flexible for further applications by others.
