### ISSUE TITLE
Minor output netCDF file and meta data issues

### ISSUE THREAD

**Issue by marev711** [cerfacs-globc/icclim#16]
- Index variable name in output NetCDF should be all set to small letters (as previously agreed). For example, TN10p -> tn10p in output file.
- Index variable attribute 'units' in output NetCDF is associated to 'days' even when input argument is chosen to be '%'
- Index values for which a given condition (by its definition) is not satisfied are set to missing value. But this should be corrected in order to make distinction between grid points with no input data and those where it is not possible for an index to be defined.
- icclim.py, line: 394: var_units == 'Celcius' to be replaced by var_units == 'Celsius'

**Comment by MilkaRadojevic** [comment]
Other minor issues:

- Could be easily feasible for you to convert output index variable into 4-dimensional in form  tn10p(frequency, year, lat, lon)? Currently, we have (time, lat, lon) where size of dimension time is frequency x year. The 4-D index is a way easier to work with otherwise more manipulation of output index file when frequency is other than year is required afterwards for an user.

- Missing value should be extracted from NetCDF input file, i.e. from _FillValue (or in older NetCDF versions: missing_value). Currently, missing value is assumed to be a maximum value in an input array. But this does not take into account the case when missing value is equal to -999 (-9999). Generally, setting missing value to an identified maximum might create some issued. Thus, to check in the icclim/calc_percentile.py, starting from line 268.

- How about re-adding an input argument for calculated percentile to be saved as NetCDF array instead dictionary, in the same output file of course?

**Comment by pagecp** [comment]
Missing value problem fixed it in the fillval branch. Still need to run the tests to be sure that I did not introduce any bug, since many modifications were needed into the code.

**Comment by pagecp** [comment]
Tests ok for fillval. Merged in master.
