### ISSUE TITLE
DOC: readthedocs is showing icclim 5.2 but latest commit available is 5.1.1-dev0

### ISSUE THREAD

**Issue by pagecp** [cerfacs-globc/icclim#160]
readthedocs is showing icclim 5.2 (for example [https://icclim.readthedocs.io/en/latest/references/ecad_functions_api.html](https://icclim.readthedocs.io/en/latest/references/ecad_functions_api.html)) latest commit available is 5.1.1-dev0.
Latest pip is 5.1.0.
Maybe 5.2 should be released?

**Comment by bzah** [comment]
The  "latest" version on readthedocs is built on latest commit on master. 

On the bottom right there is a dropdown to select which version of the doc you want to explore. However, the only one available now is the "latest"... 
I'm going to look into this to enable at least the three latest versions on readthedocs. 

We should probably release 5.2 anyway, I wanted to fix bootstrap perf before it's not going to happen so soon.

**Comment by bzah** [comment]
I think you can also dynamically update the registry with:
```
from xclim.core.units import units
units.define("@alias degC = C = deg_C = Celcius")

# ...

icclim.indice(blablabla)
``

**Comment by bzah** [comment]
On [readthedocs icclim config](https://readthedocs.org/projects/icclim/versions/) page I have enabled:
- latest (built on master)
- stable (latest tag, should be the latest release)

We can also enable specific versions but, I tried with 4.2 and the build fails now because how we changed RTD configuration.
If we want to enable/disable specific versions, this would need to be done by hand.
